name: CI2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Android signing
        run: (echo ${{ secrets.KEYSTORE }} | base64 --decode) > ./tabApp/keystore.jks
        
      - name: Set Android version
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: ./tabApp/Properties/AndroidManifest.xml
          version-name: ${{ secrets.APP_VERSION }}
          version-code: ${{ github.run_number }}
          print-file: true

      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Build Android
        run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=githubactionsxamarin /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningKeyStore=keystore.jks /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} ./tabApp/tabApp.Droid.csproj
        
      - name: Setup App Center CLI
        run: npm install -g appcenter-cli

      - name: Upload Android app to App Center
        run: appcenter distribute release --silent --file ./tabApp/bin/Release/com.filipetorres.tabapp-Signed.apk --app SByteDev/GitHubActions.Xamarin-Android --group Collaborators --token ${{ secrets.APP_CENTER_TOKEN }}

