name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
env:
  NUMBER: Monday

jobs:
  Android:
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Mandatory to use the extract version from tag action
    
    - name: Start
      run: ls
      
    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      
    - name: Update AndroidManifest.xml
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: './tabApp/Properties/AndroidManifest.xml'
        version-code: ${{ env.NUMBER_OF_COMMITS }}
        version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
        print-file: true

    - name: Android
      run: |
        nuget restore
        cd tabApp
        msbuild tabApp.Droid.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug 
    - uses: actions/upload-artifact@v2
      with:
        name: Android
        path: tabApp/bin/Debug/com.filipetorres.tabapp-Signed.apk      
    - name: Setup App Center Cli
      run: npm install -g appcenter-cli
      
    - name: Upload Android App To AppCenter
      run: appcenter distribute release --silent --file ./tabApp/bin/Debug/com.filipetorres.tabapp-Signed.apk --app flipper09/Pad --group Collaborators --token ${{ secrets.APP_CENTER_TOKEN }}

