name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Android
      run: |
        nuget restore
        cd tabApp
        msbuild tabApp.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
    - name: Android Cliente
      run: |
        nuget restore
        cd tabApp.DroidClients
        msbuild tabApp.DroidClients.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

